/**
 * TSV Hessental – Sponsoren für die durchlaufende Leiste „Danke an unsere Sponsoren“.
 *
 * Wird automatisch von js/main.js geladen und auf allen Seiten unter dem Menü
 * angezeigt (zufällige Reihenfolge, Wechsel alle paar Sekunden).
 * Neuer Sponsor: einfach eine Zeile ergänzen. Reihenfolge ist egal.
 * (Stand: übernommen aus werbepartner.html)
 */

var SPONSOREN = [
  { name: "24/7 Facility Management Wagner", adresse: "Seeweg 9 · 74523 Schwäbisch Hall" },
  { name: "2M Immobilien GmbH", adresse: "Haller Straße 69 · 74538 Rosengarten" },
  { name: "Abnehmen im Liegen • Natalie Krout", adresse: "Raiffeisenstraße 1 · 74523 Schwäbisch Hall" },
  { name: "Alfred Kärcher SE & Co. KG", adresse: "Alfred-Kärcher-Straße 28-40 · 71364 Winnenden" },
  { name: "AM-Dellentechnik", adresse: "Blätteräcker 20/1, Sulzdorf · 74523 Schwäbisch Hall" },
  { name: "Autohaus Bruno Widmann GmbH & Co. KG", adresse: "Europaplatz 1 · 74523 Schwäbisch Hall" },
  { name: "Autohaus Cunzemann GmbH", adresse: "Hauptstraße 65, Sulzdorf · 74523 Schwäbisch Hall" },
  { name: "Autohaus Fahrbach GmbH", adresse: "Raiffeisenstraße 3 · 74523 Schwäbisch Hall" },
  { name: "Autohaus Schnotz", adresse: "Haller Straße 9 · 74523 Schwäbisch Hall" },
  { name: "AVV GmbH", adresse: "Dr.-Jakob-Berlinger-Weg 9 · 74523 Schwäbisch Hall" },
  { name: "Bausparkasse Schwäbisch Hall AG", adresse: "Crailsheimer Straße 52 · 74523 Schwäbisch Hall" },
  { name: "Belschner Meisterbetrieb", adresse: "Crailsheimer Straße 69 · 74523 Schwäbisch Hall" },
  { name: "Bernhardt-Lotto", adresse: "Raiffeisenstraße 22 · 74523 Schwäbisch Hall" },
  { name: "Bioladen Kleincomburg", adresse: "Kleincomburger Weg 50 · 74523 Schwäbisch Hall" },
  { name: "Bronner GmbH • Spedition – Baustoffe", adresse: "Schmollerstraße 11 · 74523 Schwäbisch Hall" },
  { name: "Bäuerliche Erzeugergemeinschaft SHA AG", adresse: "Raiffeisenstraße 16 · 74523 Schwäbisch Hall" },
  { name: "Café am Markt", adresse: "Am Markt 10 · 74523 Schwäbisch Hall" },
  { name: "Candan Mizrak • Vorwerk Kobold-Handelsvertreter", adresse: "Auf der Lerchenhöhe 18 · 74523 Schwäbisch Hall" },
  { name: "CTS Metallbau GmbH", adresse: "Lise-Meitner-Straße 3 · 74523 Schwäbisch Hall" },
  { name: "Dudis Waffelbar", adresse: "Blockgasse 1 · 74523 Schwäbisch Hall" },
  { name: "E&A erlebnis und abenteuer GmbH", adresse: "Seeweg 5 · 74523 Schwäbisch Hall" },
  { name: "Elektro Erkert GmbH", adresse: "Am Mühlenbollwerk 10 · 74523 Schwäbisch Hall" },
  { name: "Endress Motorgeräte GmbH", adresse: "Raiffeisenstraße 43 · 74523 Schwäbisch Hall" },
  { name: "Esso Station • Katip Özen", adresse: "Bühlertalstraße 30 · 74523 Schwäbisch Hall" },
  { name: "expert Handels GmbH Süd-West & Co. KG", adresse: "Raiffeisenstraße 27 · 74523 Schwäbisch Hall" },
  { name: "Fahrschule Bigfoot GmbH", adresse: "Seestraße 29 · 74405 Gaildorf" },
  { name: "Frank Jähler GmbH • Fliesenlegermeisterbetrieb", adresse: "Maria-Goeppert-Mayer-Straße 3 · 74523 Schwäbisch Hall" },
  { name: "G & S Consult GmbH", adresse: "Herdweg 40, Sulzdorf · 74523 Schwäbisch Hall" },
  { name: "Garten- und Landschaftsbau Thomas N.C.", adresse: "Im Breitloh 17 · 74523 Schwäbisch Hall" },
  { name: "GASTI Verpackungsmaschinen GmbH", adresse: "Raiffeisenstraße 8 · 74523 Schwäbisch Hall" },
  { name: "Georg Gaukel GmbH", adresse: "Lagerweg 3, Tüngental · 74523 Schwäbisch Hall" },
  { name: "Globus Baumarkt", adresse: "Raiffeisenstraße 22 · 74523 Schwäbisch Hall" },
  { name: "Gronbach GmbH & Co. KG • Transporte und Baustoffe", adresse: "Raiffeisenstraße 17 · 74523 Schwäbisch Hall" },
  { name: "GWG Grundstücks- und Wohnungsbaugesellschaft Schwäbisch Hall mbH", adresse: "Marktstraße 4 · 74523 Schwäbisch Hall" },
  { name: "Haller Container Service • Matthias Küfer", adresse: "Emmerweg 16/1 · 74523 Schwäbisch Hall" },
  { name: "Hessental Apotheke • Jochen de Lenardis", adresse: "Grauwiesenweg 2 · 74523 Schwäbisch Hall" },
  { name: "HGE Haller Grundstücks- und Erschließungsgesellschaft mbH", adresse: "Am Markt 7/8 · 74523 Schwäbisch Hall" },
  { name: "Hirsch & Wölfl GmbH", adresse: "Im Städtle 29 · 74541 Vellberg" },
  { name: "Hochbau Kugele GmbH", adresse: "Beilsteinstraße 48/1, Gailenkirchen · 74523 Schwäbisch Hall" },
  { name: "Hohenloher Molkerei eG", adresse: "Raiffeisenstraße 4 · 74523 Schwäbisch Hall" },
  { name: "Holzbau Gruchmann", adresse: "Gerstenäcker 12 · 74523 Schwäbisch Hall" },
  { name: "Holzbau Lang Holzfachmarkt GmbH", adresse: "Mühlstraße 14-16 · 74545 Michelfeld" },
  { name: "Hüfner Möbelspedition GmbH", adresse: "Neubergstraße 19 · 74523 Schwäbisch Hall" },
  { name: "Ing.-Büro für Statik und Baukonstruktion Baumann", adresse: "Hopfengarten 26 · 74523 Schwäbisch Hall" },
  { name: "Insektenschutzgitter Waldenmaier GmbH & Co. KG", adresse: "Raiffeisenstraße 41 · 74523 Schwäbisch Hall" },
  { name: "Jane Bar", adresse: "Sparkassenplatz 5 · 74523 Schwäbisch Hall" },
  { name: "Kantine 26 – Live & Club Schwäbisch Hall", adresse: "Alfred-Leikam-Straße 7 · 74523 Schwäbisch Hall" },
  { name: "Karosserie Kramlich", adresse: "Maria-Goeppert-Mayer-Straße 5 · 74523 Schwäbisch Hall" },
  { name: "Kaufland Filiale Schwäbisch Hall – Hessental", adresse: "Raiffeisenstraße 22 · 74523 Schwäbisch Hall" },
  { name: "Koch Auto.Gruppe GmbH", adresse: "Johanniterstraße 57 · 74523 Schwäbisch Hall" },
  { name: "Kratschmayer Kälte- und Klimatechnik GmbH", adresse: "Seeweg 18 · 74523 Schwäbisch Hall" },
  { name: "KW automotive GmbH", adresse: "Aspachweg 14 · 74427 Fichtenberg" },
  { name: "Kühne Sanitär u. Flaschnerei", adresse: "Einkornstraße 28 · 74523 Schwäbisch Hall" },
  { name: "Landbäckerei Tauberschmidt", adresse: "Kirchklingenweg 2/3, Rieden · 74538 Rosengarten" },
  { name: "Landhaus Wolf", adresse: "Karl-Kurz-Straße 2 · 74523 Schwäbisch Hall" },
  { name: "Landmetzgerei Setzer", adresse: "Birkichstraße 2 · 74549 Wolpertshausen" },
  { name: "Lukas Dürr Media GmbH", adresse: "Stauffenbergstraße 8 · 74523 Schwäbisch Hall" },
  { name: "Löwenbrauerei Fr. Erhard GmbH & Co. KG", adresse: "Ritterstraße 6 · 74523 Schwäbisch Hall" },
  { name: "M und S Gartenbau GbR", adresse: "Sulzdorfer Straße 16 · 74523 Schwäbisch Hall" },
  { name: "marbet Marion & Bettina Würth GmbH & Co. KG", adresse: "Karl-Kurz-Straße 44 · 74523 Schwäbisch Hall" },
  { name: "Markovic GmbH", adresse: "Zeppelinstraße 2 · 74632 Neuenstein" },
  { name: "McDONALD´s Restaurant", adresse: "Daimlerstraße 72 · 74545 Michelfeld" },
  { name: "Media-Office", adresse: "Katharinenstraße 2 · 74523 Schwäbisch Hall" },
  { name: "Michael Bölz • Elektroinstallationen", adresse: "Roßhöhe 4 · 74523 Schwäbisch Hall" },
  { name: "Montage Fenster und Türen • Sergej Pfeifer", adresse: "Im Hardt 54 · 74523 Schwäbisch Hall" },
  { name: "Niro Media GmbH", adresse: "Eckartshäuser Straße 32 · 74532 Ilshofen" },
  { name: "NKL GmbH • Funk-Entstör-Technik", adresse: "Birkichstraße 15 · 74549 Wolpertshausen" },
  { name: "OH Outlet Hohenlohe GmbH & Co. KG", adresse: "Süßwiesenstraße 20/1 · 74549 Wolpertshausen" },
  { name: "Pichler e.K.", adresse: "Rudolf-Then-Straße 20 · 74544 Michelbach/Bilz" },
  { name: "qubixx – StadtMitteHotel", adresse: "Weilerwiese 3 · 74523 Schwäbisch Hall" },
  { name: "RB Elektro Systems GmbH & Co.KG", adresse: "Max-Planck-Straße 10 · 74523 Schwäbisch Hall" },
  { name: "Röwisch Wohnbau", adresse: "Am Kreuzstein 9 · 74523 Schwäbisch Hall" },
  { name: "Saunapark im Schenkenseebad", adresse: "Schenkenseestraße 76 · 74523 Schwäbisch Hall" },
  { name: "Schrott-Zilli GmbH • Entsorgungsfachbetrieb", adresse: "Herdweg 34, Sulzdorf · 74523 Schwäbisch Hall" },
  { name: "Sonneck Gaststättenbetriebs GmbH", adresse: "Fischweg 2, Gottwollshausen · 74523 Schwäbisch Hall" },
  { name: "Sparkasse Schwäbisch Hall Crailsheim", adresse: "Hafenmarkt 1 · 74523 Schwäbisch Hall" },
  { name: "SportShop Schwerin GmbH", adresse: "Amselweg 25 · 74423 Obersontheim" },
  { name: "SPS electronic GmbH", adresse: "Eugen-Bolz-Straße 8 · 74523 Schwäbisch Hall" },
  { name: "Stadt-gut-Hotel & Gasthof Goldener Adler", adresse: "Am Markt 11 · 74523 Schwäbisch Hall" },
  { name: "Stadtwerke Schwäbisch Hall GmbH", adresse: "An der Limpurgbrücke 1 · 74523 Schwäbisch Hall" },
  { name: "Südwest Presse Hohenlohe GmbH & Co. KG", adresse: "Haalstraße 5-7 · 74523 Schwäbisch Hall" },
  { name: "Thai Sterne Imbiss • Vereinsheim TSV Hessental", adresse: "Im Wachholder · 74523 Schwäbisch Hall" },
  { name: "Tobias Ohnesorg • Maler- und Lackierbetrieb", adresse: "Hirtengasse 9 · 74523 Schwäbisch Hall" },
  { name: "Total Station • Katip Özen", adresse: "Egerländer Weg 2 · 74523 Schwäbisch Hall" },
  { name: "VR Bank Heilbronn Schwäbisch Hall eG", adresse: "Dietrich-Bonhoeffer-Platz 1 · 74523 Schwäbisch Hall" },
  { name: "Walk in Tattoo", adresse: "Im Buchhorn 2, Michelfeld · 74523 Schwäbisch Hall" },
  { name: "Weinz Gebäudereinigung GbR", adresse: "Karl-Friedrich-Binder-Straße 14 · 74523 Schwäbisch Hall" },
  { name: "WER Haustechnik", adresse: "Bückäckerstraße 36, Sulzdorf · 74523 Schwäbisch Hall" },
  { name: "Wildbadquelle Mineralbrunnen GmbH & Co. KG", adresse: "Ritterstraße 6 · 74523 Schwäbisch Hall" },
  { name: "Windmüller GmbH", adresse: "Steinbeisweg 19 · 74523 Schwäbisch Hall" },
  { name: "Zanger Absturzsicherungen", adresse: "Hans-Georg-Albrecht-Weg 11 · 74523 Schwäbisch Hall" },
  { name: "Zerspanungstechnik Belschner GmbH", adresse: "Eberhard-Herzog-Straße 35 · 74423 Obersontheim" },
  { name: "Zur Weintenne • Familie Reber", adresse: "Im Katzenzipfel 6 · 74523 Schwäbisch Hall" }
];
